spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/formout
spring.datasource.username=formout
spring.datasource.password=formout

spring.jpa.hibernate.ddl-auto=validate

app.security.clerk-issuer=https://concrete-grouse-746.clerk.accounts.dev
app.security.clerk-jwk-set-uri=https://concrete-grouse-746.clerk.accounts.dev/.well-known/jwks.json
