spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/formout
spring.datasource.username=formout
spring.datasource.password=formout

spring.jpa.hibernate.ddl-auto=validate
